{{- $root := . -}}
{{- range $role := .Values.clusterRoles }}
{{- $_ := required (printf "%s.associateServiceAccount" $role) $role.associateServiceAccount }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $role.associateServiceAccount }}
{{- end }}
